# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-11 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201005_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.CharField(blank=True, choices=[('online', '网络班'), ('offline_weekend', '面授班(周末)'), ('offline_fulltime', '面授班(脱产)')], max_length=64, null=True, verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.CharField(choices=[('Linux', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发'), ('Go语言开发', 'Go高级开发')], max_length=64, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Linux', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发'), ('Go语言开发', 'Go高级开发')], max_length=28, verbose_name='咨询课程'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='course',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发'), ('Go语言开发', 'Go高级开发')], default='N/A', max_length=64, null=True, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.IntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (75, 'B-'), (70, 'C+'), (60, 'C'), (40, 'C-'), (-50, 'D'), (-1, 'N/A'), (-100, 'COPY')], default=-1, verbose_name='本节成绩'),
        ),
    ]
