# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
