# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-10-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20201012_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.PositiveIntegerField(default=50, verbose_name='菜单权重'),
        ),
    ]
